git:
  depth: 10
sudo: false
language: node_js
cache:
  yarn: true
  directories:
    - node_modules

node_js:
  - '9'
  - '8'
  - '6'


before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash

install: yarn --ignore-engines

script:
  - 'if [ "$PATH" = "test" ]; then make test-ci; fi'
  - 'if [ "$PATH" = "lint" ]; then make lint && make flow; fi'

matrix:
  fast_finish: true
  include:
    - env: PATH="packages/apollo"
    - env: PATH="packages/core"
    - env: PATH="packages/express"
    - env: PATH="packages/registry"
